### ISSUE TITLE
Plasma6 defaults

### ISSUE THREAD

**Issue by lgoette** [nix-community/plasma-manager#146]
Hey there,
I just recognized that the defaults set by plasma-manager are the defaults for plasma 5.
In Plasma 6 some defaults are changed to make more sense as seen here: [https://kde.org/announcements/megarelease/6/](https://kde.org/announcements/megarelease/6/).

I think there should be an option where the user can set which plasma version he is using or (if its possible) plasma-manager recognizing the plasma version.

**Comment by magnouvean** [comment]
The solution to this would be the [plasma 5 branch](https://github.com/pjones/plasma-manager/tree/plasma-5), see the [README section about this](https://github.com/pjones/plasma-manager/tree/plasma-5?tab=readme-ov-file#supported-versions). I'm not sure what you mean by defaults though, `plasma-manager` shouldn't really have many default options ideally, but there may be some. Do you have any examples of outdated defaults?

**Comment by lgoette** [comment]
Ah I see. The plasma5 branch makes sense. 
A good example would be the `clickItemTo` option. In Plasma 6 it is `select` by default. But plasma-manager sets it to `open` by default, because in plasma5 `open` was the default.
Here is the line, where the default is set [workspace module](https://github.com/pjones/plasma-manager/blob/trunk/modules/workspace.nix#L25)
I dont know if more default-settings are affected, but here are all changes regarding that topic in plasma6: [https://community.kde.org/Plasma/Plasma_6#Changes_to_default_settings](https://community.kde.org/Plasma/Plasma_6#Changes_to_default_settings)

**Comment by magnouvean** [comment]
Ah I see. Thanks for providing this. Having the defaults based on `plasma 6` does make sense. I'll take a look at it and probably make some tweaks to ensure the defaults correspond to `plasma 6` defaults in the `trunk` branch. I might wait until `plasma 6` lands in stable (probably 24.05) though.

**Comment by magnouvean** [comment]
I have made some changes so that the above option, and some other options, default to `null` instead. This way `plasma-manager` will not tinker with the options unless specifically added in the config. This is imo the best way to solve this as it will then not be designed specifically for either `plasma 5` or `plasma 6`. I have updated other parts to default to `plasma 6` now though (for example libraries, example packages etc). I think I can close this now, but feel free to comment if anyone sees something in the `trunk` branch which seem unnatural for `plasma 6`.
