### ISSUE TITLE
hotkeys trigger disappearing when boot 

### ISSUE THREAD

**Issue by RMTT** [nix-community/plasma-manager#16]
My hotkeys configuration:
```nix
{
hotkeys.commands = {
         "alacritty" = {
           comment = "default terminal";
           key = "Meta+Return";
           command = "alacritty";
         };
  
         "dropdown" = {
           comment = "dropdown terminal";
          key = "Meta+`";
          command = ''tdrop -mtair -f "--class dropdown" alacritty'';
        };
      };
}
```
For example, after configure that and reboot, it works:
```
[Data_1Triggers0]
  Key=Meta+Return
 Type=SHORTCUT
  Uuid={6880261a8a14507fd975a5fe7d8f559bdd7d64f5f5dc77abb2482d70b4adc488}
```
But when i reboot again, the key of trigger disappeared:
```
[Data_1Triggers0]
  Key=
 Type=SHORTCUT
  Uuid={6880261a8a14507fd975a5fe7d8f559bdd7d64f5f5dc77abb2482d70b4adc488}
```
And reboot again. the key appeared again:
```
[Data_1Triggers0]
  Key=Meta+Return
 Type=SHORTCUT
  Uuid={6880261a8a14507fd975a5fe7d8f559bdd7d64f5f5dc77abb2482d70b4adc488}
```

I have no idea why trigger key toggle between appear and disappear, but i found a workaround, just run the configuration script once or several times manually, for example:
```shell
/nix/store/vsmybd99mxpkf9677p2mn4ikbymy3xnm-plasma-config
```

**Comment by pjones** [comment]
I bet this would be fixed by getting #1 and #2 resolved.

**Comment by opl-** [comment]
According to [this Reddit comment](https://old.reddit.com/r/kde/comments/de3ooj/trying_to_add_shortcuts_to_khotkeysrc_by_scripts/f2usu3c/), khotkeys is being phased out. Last week the khotkeys repository [was replaced](https://invent.kde.org/plasma/khotkeys/-/commit/3f87874556cfdf16cc5d2a5125fe0d3edf80e253) with a README saying *"KHotkeys is no longer maintained. The last maintained version is in the Plasma/5.27 branch."* It also links to [phabricator issue T2050](https://phabricator.kde.org/T2050): *"sunsetting KHotKeys"*.

However, the Reddit comment linked before mentions the UUIDs and the keybind being repeated in `kglobalshortcutsrc`, which is indeed the case.

I did some work to correctly generate UUIDs instead of using a hash, which I believe might be the reason the keybinds get reset, but having found khotkeys is no longer being maintained I did not do the last bit of work to put the same UUIDs and hotkeys in the `kglobalshortcutsrc` file. If anyone is interested in that, you can find what I have so far [here](https://github.com/opl-/plasma-manager/tree/fix/hotkey-trigger-uuids).

**Comment by RMTT** [comment]
I also found the `khotkeys` will be removed in the future, we should use `kglobalshortcutsrc` now. @opl- Thanks for your response.
