### ISSUE TITLE
Add option `everythingImmutable` or `immutableByDefault`

### ISSUE THREAD

**Issue by Asqiir** [nix-community/plasma-manager#217]
I would like to have an option that makes *everything I set with plasma-manager* `immutable`.

Proposed name:
(1) `everythingImmutable`
(2) `forceImmutable`
(3) `immutableByDefault`

Proposed behaviour:
* every option for which a value but no mutability/persistency behaviour was specified: this is now immutable
* every option where `persistent` is specified: stays persistent
* when something is explicitly marked as `immutable = false` then (for 1 or 2) fail the build or (3) make not immutable. I don't have a strong intuition on that.

@magnouvean I think that goes with the spirit of your other proposal of changing the override behaviour. What do you think?

**Comment by magnouvean** [comment]
I reckon option ´3´ makes the most sense since it gives more control to the user and since the implementation would be the most elegant. The only challenge is that at the moment immutability and persistence are incompatible so that will take some work figuring out how we can allow for combining these two in a way that makes sense.
