### ISSUE TITLE
Panel disable "Mouse Wheel: cycles though tasks"

### ISSUE THREAD

**Issue by hoferbeck** [nix-community/plasma-manager#223]
Hello,

is it possible when specifiying a Panel to disable the option "Mouse Wheel: cycles though tasks"? 

Best Regards

**Comment by magnouvean** [comment]
Yes that should be possible. Assuming you are talking about the `org.kde.plasma.icontasks` widget (I can't see that option for panels) you should be able to disable it by adding `General.wheelEnabled = false` in the config for the widget, for example you could use something like the following widget:
```nix
{
  name = "org.kde.plasma.icontasks";
  config.General = {
    launchers = [
      "applications:org.kde.dolphin.desktop"
      "applications:org.kde.konsole.desktop"
    ];
   wheelEnabled = false; # Disables mouse wheel scrolling.
  };
}
```
I haven't tested this though, but hopefully something like this should work.

**Comment by hoferbeck** [comment]
Yes that was that i was searching!

Is there way to discover / lookup the options that are available?

**Comment by magnouvean** [comment]
At the moment there isn't really a proper way to see all the options for plasma-manager, but we are working on it, maybe by getting it up on https://search.nixos.org/flakes or our own version of it. We want to move the project to nix-community first though since this would change the url for the repo, but hopefully we can get something going rather soon. In the case of panels though this wouldn't really help you as what the `config` option for the widget essentially does is write some keys in the `Configuration` section for the widget in `plasma-org.kde.plasma.desktop-appletsrc`. This way it's sort of like an `extraConfig` option which you might be familiar from in other nix-projects, i.e. it doesn't have any predefined allowed options. How I found the key was by enabling the setting in the GUI and checking which keys had been added for the configuration of the icontasks widget in `plasma-org.kde.plasma.desktop-appletsrc`. For panels this file is where pretty much all the configuration is stored.
