### ISSUE TITLE
[Feature]: Add option to control the data range of system monitor sensors

### ISSUE THREAD

**Issue by Preons0** [nix-community/plasma-manager#247]
It could be good if the system monitor widget had the ability to set a non-automatic range. Currently, I couldn't find the option if it does exist.

**Comment by GraisenEdwards** [comment]
Can you do
```nix
{
          systemMonitor = {
            title = "Upload Speed";
            displayStyle = "org.kde.ksysguard.piechart";
            sensors = [{
              name = "network/all/upload";
              label = "Upload Speed";
              color = "235,203,139";
            }];
          };
          config.foo.bar = "baz";
        }
}
```
Or just in general use one of the high level widgets and set low level options for them?

**Comment by magnouvean** [comment]
I don't think that will work since the setting will need to be in the specific widget category in `plasma-org.kde.plasma.desktop-appletsrc`. With that said it should be possible if you use something like:
```nix
{
  name = org.kde.plasma.systemmonitor;
  config = ...;
}
```
(here I haven't completed the configuration, but it is possible if you spend some time finding the correct values to put in `config`).
#248 will add options for this though in the high-level widget, which is what I think is the best solution here. After that is merged you can specify `range.from` and `range.to` options for this widget. It will need some testing though as it's quite a large PR (it involves a lot of refactoring as well), so if anyone reading this has time to test it on their config and see if everything works (and comment how it does in the PR) that would be helpful :). It's pretty much done as well so probably will be in `plasma-manager` quite soon :)
