### ISSUE TITLE
ApplicationTitleBar widget module is missing BorderlessMaximizedWindows option

### ISSUE THREAD

**Issue by NovaViper** [nix-community/plasma-manager#264]
Hey there's a behavior option for Application Title Bar that is missing, it's the Borderless Maximized Windows (circled in the screenshot)
![image](https://github.com/user-attachments/assets/42249e0d-39be-41f5-95f8-860c8ff51d64)

If I declaratively setup plasma-manager (with `overrideConfig`, this option gets reset as it is not declared in plasma-manager at all; which is rather annoying to have to set everytime I activate home-manager.

**Comment by HeitorAugustoLN** [comment]
There is no way to set this option via application-title-bar widget-specific options. Because there is no option in the widget [configuration](https://github.com/antroids/application-title-bar/blob/main/package/contents/config/main.xml) files.

But this option just sets a kwinrc configuration. So you could simply use plasma-manager to configure kwinrc with this option:

```nix
programs.plasma.configFile."kwinrc"."Windows"."BorderlessMaximizedWindows" = true;
```

**Comment by HeitorAugustoLN** [comment]
That's why you don't need to apply the configuration for it to work. Because it runs `kwriteconfig` to configure this option to true

**Comment by NovaViper** [comment]
#265 resolves this, will close now. Thank you!
