### ISSUE TITLE
"[]" escaped to "\x5b\x5d" for no apparent reason

### ISSUE THREAD

**Issue by Asqiir** [nix-community/plasma-manager#296]
I used to have "[]" in my `programs.kate.editor.brackets` since the beginning. By now, these are escaped to "\x5b\x5d" when written to `config/katerc` for no apparent reason. I tried to locate faulty the commit, but I couldn't find it yet.

I would like to continue having these brackets in this config option. I would like to know what changed, and either fix the new escaping behaviour, or document it in the description.

**Comment by magnouvean** [comment]
Is this something which only happened recently? I think we have started escaping `[` and `]` ever since 4b56c71c9cdb9728316cbb5dd99446b31c585913. Also, does this mean that the functionality doesn't work anymore?

I don't know how to best solve this though as I believe escaping these values to comply with kde config-file formats is a good thing in general. Perhaps one solution could be to add a new option `escape` for each key (which defaults to `true`), which allows us to not escape certain keys if there is a need for it (such as in this case).

**Comment by Asqiir** [comment]
The functionality fails when one of these escape sequences ends up in the strings.

I do not understand why these brackets need to be escaped when inside a string, that means, I cannot tell what kind of solution would be good.

**Comment by magnouvean** [comment]
Tbh I've never quite understood it either why KDE has these certain character-escaping rules, but it seems to have them. That's why for example `kwriteconfig` is unable to write `[$i]` (i.e. immutable keys) to config-files. Nevertheless in cases like this there should be some way to disable this escaping. I think the proposed solution would be a good way, as it allows us to disable this character-escaping manually, which we can utilize in the kate-module.

I also seem to remember `[` and `]` always being escaped even when we wrote the module initially, but there could have been an update in kate or something so that this escaped syntax all of a sudden breaks.
