### ISSUE TITLE
Energy settings reset after reboot

### ISSUE THREAD

**Issue by urioTV** [nix-community/plasma-manager#329]
Just enabling plasma-manager with programs.plasma.enable = true makes energy setting does not save. I cannot change when I want my display to turn off and when my laptop should go to sleep.

Disabling plasma-manager fixes that. Even If I have no additional settings in plasma-manager problems occurs.

**Comment by HeitorAugustoLN** [comment]
Unless `overrideConfig` is enabled, it really shouldn't happen. I will try to reproduce it. But you can declare your energy settings with the `powerdevil` module.

**Comment by urioTV** [comment]
That's really strange. Honestly I don't know if it was happening from the beginning or appeared while I was using plasma-manager. Once I noticed it I tried to debug it and I see that just enabling plasma-manager breaks energy settings.

**Comment by Chwiggy** [comment]
I have noticed a similar behaviour change since reinstalling my configs including plasma-manager recently. This issue did not exist before a few weeks ago.

But i have neither enabled `overrideConfig` nor actually declared my `powerdevil` settings in plasma-manager. I can set them manually in the gui or by writing the respective `powerdevilrc` config, but both these options do not persist through a system reboot, when that file gets overwritten with a 0 Byte config

**Comment by urioTV** [comment]
Right now I'm using power devil to declare my config however the issue still persist.

**Comment by Chwiggy** [comment]
setting an explicit `powerdevil` config with plasma manager as mentioned above does seem to work too. just leaving the power management to manual config or to rc2nix seems to cause the odd behaviour. but yeah this still seems to be an odd state, where leaving things to manual settings after config is not an option.

**Comment by HeitorAugustoLN** [comment]
> Right now I'm using power devil to declare my config however the issue still persist.

It is happening with the configuration that is being declared?

**Comment by HeitorAugustoLN** [comment]
I would say it is probably due to the way powerdevil module is working.
