### ISSUE TITLE
Enabling plasma-manager conflicts with home.file kglobalshortcutrc backup

### ISSUE THREAD

**Issue by Moe1369** [nix-community/plasma-manager#345]
Instead of using the hotkeys module I use my dotfile. When I do that a rebuild fails with the message:

`Aug 31 22:35:01 workstation hm-activate-mo[42136]:     write_configs(d, reset_files, immutable_by_default)
Aug 31 22:35:01 workstation hm-activate-mo[42136]:   File "/nix/store/lh2hfqbclxmdxldb1997af5mxx2xb0ss-write_config.py", line 317, in write_configs
Aug 31 22:35:01 workstation hm-activate-mo[42136]:     config.save()
Aug 31 22:35:01 workstation hm-activate-mo[42136]:   File "/nix/store/lh2hfqbclxmdxldb1997af5mxx2xb0ss-write_config.py", line 278, in save
Aug 31 22:35:01 workstation hm-activate-mo[42136]:     with open(self.filepath, "w", encoding="utf-8") as f:
Aug 31 22:35:01 workstation hm-activate-mo[42136]:          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 31 22:35:01 workstation hm-activate-mo[42136]: OSError: [Errno 30] Read-only file system: '/home/mo/.config/kglobalshortcutsrc`

to reproduce:
  home.file.".config/kglobalshortcutsrc".source = ../../../dotfiles/kglobalshortcutsrc;
  programs.plasma.enable = true;

 when I disable plasma manager by setting the value to false it works.

**Comment by magnouvean** [comment]
I assume there is no `plasma-manager` configuration outside of `programs.plasma.enable = true;`?
In general `plasma-manager` will need write-access to lots of different configuration-files in `~/.config`, which is probably what is causing the problem here, since you have symlinked this to the nix-store (which is read-only) using home-manager. With that said if there is no configuration in `programs.plasma.shortcuts` I guess `plasma-manager` shouldn't need to have write-access to `kglobalshortcutsrc`, so maybe we can find a fix for this.

Until then though I can perhaps recommend to instead of symlinking this file, to instead use the `programs.plasma.shortcuts` module if possible, and then just not symlink the file (imo this is a better way to do this in most cases anyway).

**Comment by Moe1369** [comment]
Ok I could do that but issue is I have every single shortcut set in kglobalshortcutrc which would lead to a long plasma config file.

**Comment by HeitorAugustoLN** [comment]
You could try using `mkOutOfStoreSymlink` to symlink it without conflicting with plasma-manager

**Comment by Moe1369** [comment]
Thx for showing me the function but then the file then the repo has to on disk right?

**Comment by HeitorAugustoLN** [comment]
Here is how you can use this function

```nix
{ config, ... }:
{
  home.configFile."kglobalshortcutsrc".source = config.lib.file.mkOutOfStoreSymlink ./path/to/kglobalshortcutsrc
}
```
