### ISSUE TITLE
Declaring favorites app in Kickoff through plasma-manager

### ISSUE THREAD

**Issue by mapperfr** [nix-community/plasma-manager#376]
Hi, 
I'm trying to figure out how to declare the favorites pinned in Kickoff. I looked on the Kickoff widget file but couldn't find anything useful. Is it possible? 
For the moment, the issue is that the applications I add to favorites become "unclickable" (= icons are visible but nothing happens when I click) every time I hit ```nixos-rebuild switch```. 
Any help would be greatly appreciated, thanks!

**Comment by HeitorAugustoLN** [comment]
When I added the `kickoff` module, I didn't add the `favorites` option because couldn't make it work.
But looking into it now, it looks like the favorites are being set in `$XDG_CONFIG_HOME/kactivitymanagerd-statsrc`. So you can set it there. But I would recommend against it, since it is being set with the containment id of the applet, and if you are using `overrideConfig`, it gets changed overwritten every boot. But currently that should be the only available option for doing so.

**Comment by mapperfr** [comment]
Thanks @HeitorAugustoLN for this detailed explanation.
Does it appear to you as an expected behavior that the favorites unpin themselves, or become unreactive, each time I regenerate the config? Any suggestion for a workaround?

**Comment by HeitorAugustoLN** [comment]
> Thanks @HeitorAugustoLN for this detailed explanation. Does it appear to you as an expected behavior that the favorites unpin themselves, or become unreactive, each time I regenerate the config? Any suggestion for a workaround?

When setting in the widget, they didn't even appear when I tested. I never tried setting in `$XDG_CONFIG_HOME/kactivitymanagerd-statsrc`

**Comment by mapperfr** [comment]
Thanks! As a workaround I added programs shortcuts to the task manager and I don't have any issue here when I regenerate the config. I'll stick to this for the moment.

**Comment by drupol** [comment]
There might be a solution here: https://github.com/NixOS/nixpkgs/issues/414909#issuecomment-3216038215
