### ISSUE TITLE
trivial(docs): en_US or en_UK?

### ISSUE THREAD

**Issue by SigmaSquadron** [nix-community/plasma-manager#399]
I'm going through every option, and it's not exactly clear if we should present options in American English or <del>proper english</del> British English. Most option descriptions seem to use American English, but there's the occasional *colour* in some options.

We should probably define a specific preference for current and future modules.

**Comment by magnouvean** [comment]
I think the most standard is american english so this should probably be the naming-convention. I haven't seen much en_UK in this repo, only two words in some descriptions (where it said "colour" instead of "color"). Were there any more off the top of your head which uses en_UK?

Edit: I see you have fixed some of those in #400, so that's good!
